
CREATE TABLE users(
	ID INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	mail VARCHAR(40) NOT NULL UNIQUE,
	pass CHAR(40) NOT NULL,
	token CHAR(40) NOT NULL DEFAULT "5dc9b72fbcef651e31ff0b484117b119e17acebd",
	name VARCHAR(40) NOT NULL,
	first_name VARCHAR(60),
	edad INT(3),
	DNI CHAR(9) NOT NULL UNIQUE,
	created DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE customers(
	ID INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	ID_user INT(10) NOT NULL,
	name VARCHAR(40) NOT NULL,
	first_name VARCHAR(100),
	DNI VARCHAR(9) NOT NULL UNIQUE,
	email VARCHAR(60) NOT NULL,
	phone_number VARCHAR(15) NOT NULL,
	address VARCHAR (100),
	city VARCHAR (50),
	country VARCHAR (40),
	CP INT (7),
	created DATETIME DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT FOREIGN KEY(ID_user) REFERENCES users(ID) ON DELETE CASCADE
);

CREATE TABLE companies(
	ID INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	name VARCHAR(80) NOT NULL,
	contact_person VARCHAR(100) NOT NULL,
	contact_phone VARCHAR(15) NOT NULL,
	contact_mail VARCHAR(60) NOT NULL,
	created DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products(
	ID INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	ID_company INT(10) NOT NULL,
	product_name VARCHAR(80) NOT NULL,
	type enum("auto", "moto", "hogar", "vida") DEFAULT null,
	created DATETIME DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT FOREIGN KEY(ID_company) REFERENCES companies(ID) ON DELETE CASCADE
);

CREATE TABLE insurances(
	ID INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	ID_customer INT(10) NOT NULL,
	ID_product INT(10) NOT NULL,
	hiring_date DATETIME DEFAULT CURRENT_TIMESTAMP,
	price FLOAT,
	commission FLOAT,
	CONSTRAINT FOREIGN KEY (ID_customer) REFERENCES customers(ID)ON DELETE CASCADE,
	CONSTRAINT FOREIGN KEY (ID_product) REFERENCES products(ID) ON DELETE CASCADE
);

INSERT INTO prueba VALUES (
	'Ruben',
	42,
	'47021682E',
	'rubenpadelone@gmail.com',
	'd341447813ce6283d705383511b34db0b3cf5598'
)